version: "2"

services:
  sonarqube:
    image: sonarqube
    restart: always
    ports:
      - "9005:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/sonar
    volumes:
      - C:\Users\ccharlton\Desktop\setupSonarPostgreWindows\sonarPostgres\sonarqube\conf:/opt/sonarqube/conf
      - C:\Users\ccharlton\Desktop\setupSonarPostgreWindows\sonarPostgres\sonarqube\data:/opt/sonarqube/data
      - C:\Users\ccharlton\Desktop\setupSonarPostgreWindows\sonarPostgres\sonarqube\extensions:/opt/sonarqube/extensions
      - C:\Users\ccharlton\Desktop\setupSonarPostgreWindows\sonarPostgres\sonarqube\lib\bundled-plugins:/opt/sonarqube/lib/bundled-plugins


  postgresql:
    image: postgres
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - data:/var/lib/postgresql/data



  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "1025:1025"
    ports:
      - "8025:8025"


volumes:
  data:
    external: true


networks:
  sonarnet:
    driver: bridge
